// https://www.w3schools.com/jsref/dom_obj_event.asp
export enum DOM_EVENT {
  LOAD = 'load',
  UNLOAD = 'unload',
  FOCUS = 'focus',
  BLUR = 'blur',
  TOGGLE = 'toggle',
  SUBMIT = 'submit',
  RESIZE = 'resize',
  SCROLL = 'scroll',
  WHEEL = 'wheel',
  PROGRESS = 'progress',
  CHANGE = 'change',
  CLICK = 'click',
  MOUSE_DOWN = 'mousedown',
  MOUSE_ENTER = 'mouseenter',
  MOUSE_LEAVE = 'mouseleave',
  MOUSE_MOVE = 'mousemove',
  MOUSE_OVER = 'mouseover',
  MOUSE_OUT = 'mouseout',
  MOUSE_UP = 'mouseup',
  TOUCH_START = 'touchstart',
  TOUCH_CANCEL = 'touchcancel',
  TOUCH_END = 'touchend',
  TOUCH_MOVE = 'touchmove',
  KEY_DOWN = 'keydown',
  KEY_PRESS = 'keypress',
  KEY_UP = 'keyup',
  STORAGE = 'storage',
  CONTEXT_MENU = 'contextmenu',
}
