export enum KEY_CODE {
  ARROW_UP = 38,
  ARROW_DOWN = 40,
  ARROW_LEFT = 37,
  ARROW_RIGHT = 39,
  BACKSPACE = 8,
  TAB = 9,
  ENTER = 13,
  SHIFT = 16,
  CONTROL = 17,
  ESC = 27,
  SPACE = 32,
  DELETE = 46,
  NUMBER_ZERO = 48,
  NUMBER_NINE = 57,
  LETTER_A = 65,
  LETTER_Z = 90,
  // command key on the mac os
  META = 91,
}
