name: CI - code check

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run check --if-present
        env:
          CI: true
